trigger:
- main

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install -y --no-install-recommends python3-venv zlib1g-dev libkrb5-dev libtinfo5
      ./build.sh
    env:
      CXX: g++-9
    workingDirectory: build
  - task: PublishTestResults@2
    inputs:
      searchFolder: '$(System.DefaultWorkingDirectory)/build/results'
      testResultsFiles: 'bootstrap_results.xml'
      testRunTitle: 'Native Tests (Linux)'
  - publish: $(System.DefaultWorkingDirectory)/build/packages
    artifact: Packages (Linux)

- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: ./build.cmd
    workingDirectory: build
  - task: PublishTestResults@2
    inputs:
      mergeTestResults: true
      searchFolder: '$(System.DefaultWorkingDirectory)/build/results'
      testResultsFormat: 'VSTest'
      testResultsFiles: '*.trx'
      testRunTitle: 'Managed Tests'
  - task: PublishTestResults@2
    inputs:
      searchFolder: '$(System.DefaultWorkingDirectory)/build/results'
      testResultsFiles: 'bootstrap_results.xml'
      testRunTitle: 'Native Tests (Windows)'
  - publish: $(System.DefaultWorkingDirectory)/build/packages
    artifact: Packages (Windows)

- job: CodeCoverage
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install -y --no-install-recommends python3-venv
      ./build.sh --target=GenerateCoverage
    env:
      CXX: g++-9
    workingDirectory: build
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/build/results/merged/Cobertura.xml'
