trigger:
- main

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - script: ./build.sh
    env:
      CXX: g++-9
    workingDirectory: build

- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: ./build.cmd
    workingDirectory: build
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '*.trx'
      searchFolder: '$(System.DefaultWorkingDirectory)/build/results'
      testRunTitle: 'Managed Tests'
