trigger:
- main

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - script: ./build.sh
    env:
      CXX: g++-9
    workingDirectory: build

- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: ./build.cmd
    workingDirectory: build
